package com.vanced.manager.ui.theme

import androidx.compose.ui.graphics.Color

val primaryColor = Color(defAccentColor)
val primaryColorVariant = primaryColor.copy(alpha = 0.25f)

val darkSurface = Color.Black
val darkOnSurface = Color(0xFFD5D5D5)

val lightSurface = Color.White
val lightOnSurface = Color.Black

val md_theme_light_primary = Color(0xFF0054d9)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFdae2ff)
val md_theme_light_onPrimaryContainer = Color(0xFF00174a)
val md_theme_light_secondary = Color(0xFFc00020)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffdad6)
val md_theme_light_onSecondaryContainer = Color(0xFF410005)
val md_theme_light_tertiary = Color(0xFF943896)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd6fa)
val md_theme_light_onTertiaryContainer = Color(0xFF37003c)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfefbff)
val md_theme_light_onBackground = Color(0xFF1b1b1e)
val md_theme_light_surface = Color(0xFFfefbff)
val md_theme_light_onSurface = Color(0xFF1b1b1e)
val md_theme_light_surfaceVariant = Color(0xFFe2e2ec)
val md_theme_light_onSurfaceVariant = Color(0xFF44464e)
val md_theme_light_outline = Color(0xFF75767f)
val md_theme_light_inverseOnSurface = Color(0xFFf2f0f5)
val md_theme_light_inverseSurface = Color(0xFF303033)

val md_theme_dark_primary = Color(0xFFb1c5ff)
val md_theme_dark_onPrimary = Color(0xFF002a77)
val md_theme_dark_primaryContainer = Color(0xFF003ea6)
val md_theme_dark_onPrimaryContainer = Color(0xFFdae2ff)
val md_theme_dark_secondary = Color(0xFFffb3af)
val md_theme_dark_onSecondary = Color(0xFF69000c)
val md_theme_dark_secondaryContainer = Color(0xFF920016)
val md_theme_dark_onSecondaryContainer = Color(0xFFffdad6)
val md_theme_dark_tertiary = Color(0xFFffa9fc)
val md_theme_dark_onTertiary = Color(0xFF5a0061)
val md_theme_dark_tertiaryContainer = Color(0xFF781c7c)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd6fa)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1b1e)
val md_theme_dark_onBackground = Color(0xFFe3e1e6)
val md_theme_dark_surface = Color(0xFF1b1b1e)
val md_theme_dark_onSurface = Color(0xFFe3e1e6)
val md_theme_dark_surfaceVariant = Color(0xFF44464e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc6c6d0)
val md_theme_dark_outline = Color(0xFF8f909a)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1e)
val md_theme_dark_inverseSurface = Color(0xFFe3e1e6)

val seed = Color(0xFF2e73ff)
val error = Color(0xFFba1b1b)